pipeline {
  stages {
    stage("Build") {

    }

    stage("Test") {

    }
  }

  post {
    always {
      xunit(thresholds: [ skipped(failureThreshold: '0'), failed(failureThreshold: '0') ],
            tools: [ GoogleTest(pattern: 'reports/*.xml') ])
    }
  }
}