pipeline {
  stages {
    stage("Build") {
      steps {
        cmakeBuild(
          generator: 'Make',
          buildDir: 'build',
          sourceDir: 'Sources',
          installation: 'InSearchPath'
        )
      }
    }
  }

  post {
    always {
      xunit(thresholds: [ skipped(failureThreshold: '0'), failed(failureThreshold: '0') ],
            tools: [ GoogleTest(pattern: 'reports/*.xml') ])
    }
  }
}